version: '3.3'

services:

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: my_db

  web:
    build: ./project/
    depends_on:
      - db
    command: python manage.py migrate
    volumes:
      - ./project/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./project/.env

volumes:
  pgdata: