version: '3.3'

services:

  db:
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: my_db

  web:
    build: ./project/
    depends_on:
      - db
    volumes:
      - static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./project/.env

  nginx:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - ./project/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/www/html/static
    ports:
      - 80:80


volumes:
  pgdata:
  static: